### ISSUE TITLE
base_uri

### ISSUE THREAD

**Issue by coupontom** [cmer/sendyr#1]
Why use URI.join? If you have sendy installed anywhere but the root url (like I do) , this will create wrong urls. 

With a url of http://sendy.example.com/sendy, URI.join results in 
http://sendy.example.com/subscribe 
instead of 
http://sendy.example.com/sendy/subscribe

def url_for(path)
    URI.join(@base_uri, path).to_s
end

Nice gem though!

**Comment by ssoulless** [comment]
Thanks, your annotation was helpful
